0.0.4alpha from https://sourceforge.net/projects/gephex/files/gephex/

diff --git a/base/src/net/Makefile.in b/base/src/net/Makefile.in
--- a/base/src/net/Makefile.in
+++ b/base/src/net/Makefile.in
@@ -26,8 +26,10 @@ datadir = @datadir@
 sysconfdir = @sysconfdir@
 sharedstatedir = @sharedstatedir@
 localstatedir = @localstatedir@
+libdir = @libdir@
 infodir = @infodir@
 mandir = @mandir@
+includedir = @includedir@
 oldincludedir = /usr/include
 
 DESTDIR =
@@ -36,7 +38,7 @@ pkgdatadir = $(datadir)/@PACKAGE@
 pkglibdir = $(libdir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
 
-top_builddir = ../..
+top_builddir = ../../..
 
 ACLOCAL = @ACLOCAL@
 AUTOCONF = @AUTOCONF@
@@ -58,53 +60,69 @@ POST_UNINSTALL = :
 host_alias = @host_alias@
 host_triplet = @host@
 AS = @AS@
+AVIFILE_CONFIG = @AVIFILE_CONFIG@
+AVIFILE_CXXFLAGS = @AVIFILE_CXXFLAGS@
+AVIFILE_LDFLAGS = @AVIFILE_LDFLAGS@
 CC = @CC@
 CXX = @CXX@
 DLLTOOL = @DLLTOOL@
 ECHO = @ECHO@
+EFFECTV_SRC_DIR = @EFFECTV_SRC_DIR@
 EXEEXT = @EXEEXT@
+LEX = @LEX@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
 MAKEINFO = @MAKEINFO@
+MOC = @MOC@
 OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
 PACKAGE = @PACKAGE@
-PYTHON = @PYTHON@
+QT_CXXFLAGS = @QT_CXXFLAGS@
+QT_LIBS = @QT_LIBS@
 RANLIB = @RANLIB@
+SDL_CFLAGS = @SDL_CFLAGS@
+SDL_CONFIG = @SDL_CONFIG@
+SDL_LIBS = @SDL_LIBS@
 STRIP = @STRIP@
+UIC = @UIC@
 VERSION = @VERSION@
+YACC = @YACC@
 
-baseincludedir = @includedir@/gephex
-includedir = @includedir@/gephex/net
-libdir = @libdir@/gephex
+TESTS = nettest
 
-noinst_PROGRAMS = nettest
-lib_LIBRARIES = libnetwork.a
+check_PROGRAMS = nettest
+noinst_LIBRARIES = libnetwork.a
 
 libnetwork_a_SOURCES =  		netexceptions.cpp 		protocol.cpp 		tagutils.cpp 		isocket.cpp 		sotimeout.cpp 		socketutils.cpp 		tcpserversocket.cpp 		tcpclientsocket.cpp 		fdsocket.cpp 		socketadaptor.cpp 		domainserversocket.cpp 		domainclientsocket.cpp
 
-#commandmux.cpp netdispatcher.cpp  fileprotocol.cpp netprotocol.cpp clientnetsocket.cpp ervernetsocket.cpp tcpsocket.cpp udpsocket.cpp netdispatcher2.cpp
 
-include_HEADERS =  		protocol.h 		idatalistener.h 		isender.h 		netexceptions.h 		itagger.h 		itaginterpreter.h 		tagger.h 		tagger.cpp 		tagutils.h 		isocket.h 		socketutils.h 		sotimeout.h 		iclientsocket.h 		iserversocket.h 		tcpclientsocket.h 		tcpserversocket.h 		fdsocket.h 		socketadaptor.h 		tagdispatcher.h 		tagdispatcher.cpp 		domainserversocket.h 		domainclientsocket.h 		protocoltest.h 		tcpsockettest.h 		tagdispatchertest.h 		taggertest.h 		domainsockettest.h
+noinst_HEADERS =  		protocol.h 		idatalistener.h 		isender.h 		netexceptions.h 		itagger.h 		itaginterpreter.h 		tagger.h 		tagger.cpp 		tagutils.h 		isocket.h 		socketutils.h 		sotimeout.h 		iclientsocket.h 		iserversocket.h 		tcpclientsocket.h 		tcpserversocket.h 		fdsocket.h 		socketadaptor.h 		tagdispatcher.h 		tagdispatcher.cpp 		domainserversocket.h 		domainclientsocket.h 		protocoltest.h 		tcpsockettest.h 		tagdispatchertest.h 		taggertest.h 		domainsockettest.h
 
 
-INCLUDES = -I .. #${baseincludedir}
+INCLUDES = -I @srcdir@/.. -I @srcdir@/../../../util/include
 
 nettest_SOURCES =  		testmain.cpp 		block.h 		tcpsockettest.cpp 		protocoltest.cpp 		taggertest.cpp 		tagdispatchertest.cpp 		domainsockettest.cpp 		tcpsockettest.h 		protocoltest.h 		taggertest.h 		tagdispatchertest.h 		domainsockettest.h
 
 
-nettest_LDFLAGS = -L../TestFramework -L../utils -L.
-nettest_LDADD = -ltestframework -lnetwork -lutils 
+nettest_LDADD =  	-L@builddir@/../TestFramework 	-L@builddir@/../utils 	-L@builddir@ 	-ltestframework 	-lnetwork 	-lutils 
+
+
+nettest_DEPENDENCIES =  	@builddir@/../TestFramework/libtestframework.a 	@builddir@/../utils/libutils.a  	@builddir@/libnetwork.a
+
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-CONFIG_HEADER = ../../config.h
+CONFIG_HEADER = ../../../config.h
 CONFIG_CLEAN_FILES = 
-LIBRARIES =  $(lib_LIBRARIES)
+LIBRARIES =  $(noinst_LIBRARIES)
 
 
-DEFS = @DEFS@ -I. -I$(srcdir) -I../..
+DEFS = @DEFS@ -I. -I$(srcdir) -I../../..
 CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
+X_CFLAGS = @X_CFLAGS@
+X_LIBS = @X_LIBS@
+X_EXTRA_LIBS = @X_EXTRA_LIBS@
+X_PRE_LIBS = @X_PRE_LIBS@
 libnetwork_a_LIBADD = 
 libnetwork_a_OBJECTS =  netexceptions.$(OBJEXT) protocol.$(OBJEXT) \
 tagutils.$(OBJEXT) isocket.$(OBJEXT) sotimeout.$(OBJEXT) \
@@ -112,13 +130,11 @@ socketutils.$(OBJEXT) tcpserversocket.$(OBJEXT) \
 tcpclientsocket.$(OBJEXT) fdsocket.$(OBJEXT) socketadaptor.$(OBJEXT) \
 domainserversocket.$(OBJEXT) domainclientsocket.$(OBJEXT)
 AR = ar
-noinst_PROGRAMS =  nettest$(EXEEXT)
-PROGRAMS =  $(noinst_PROGRAMS)
-
+check_PROGRAMS =  nettest$(EXEEXT)
 nettest_OBJECTS =  testmain.$(OBJEXT) tcpsockettest.$(OBJEXT) \
 protocoltest.$(OBJEXT) taggertest.$(OBJEXT) tagdispatchertest.$(OBJEXT) \
 domainsockettest.$(OBJEXT)
-nettest_DEPENDENCIES = 
+nettest_LDFLAGS = 
 CXXFLAGS = @CXXFLAGS@
 CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
 LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
@@ -129,7 +145,7 @@ COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CF
 LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 CCLD = $(CC)
 LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
-HEADERS =  $(include_HEADERS)
+HEADERS =  $(noinst_HEADERS)
 
 DIST_COMMON =  Makefile.am Makefile.in
 
@@ -138,13 +154,6 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-DEP_FILES =  .deps/domainclientsocket.P .deps/domainserversocket.P \
-.deps/domainsockettest.P .deps/fdsocket.P .deps/isocket.P \
-.deps/netexceptions.P .deps/protocol.P .deps/protocoltest.P \
-.deps/socketadaptor.P .deps/socketutils.P .deps/sotimeout.P \
-.deps/tagdispatchertest.P .deps/taggertest.P .deps/tagutils.P \
-.deps/tcpclientsocket.P .deps/tcpserversocket.P .deps/tcpsockettest.P \
-.deps/testmain.P
 SOURCES = $(libnetwork_a_SOURCES) $(nettest_SOURCES)
 OBJECTS = $(libnetwork_a_OBJECTS) $(nettest_OBJECTS)
 
@@ -152,44 +161,24 @@ all: all-redirect
 .SUFFIXES:
 .SUFFIXES: .S .c .cpp .lo .o .obj .s
 $(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
-	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/net/Makefile
+	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps base/src/net/Makefile
 
-Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
 
-mostlyclean-libLIBRARIES:
+mostlyclean-noinstLIBRARIES:
 
-clean-libLIBRARIES:
-	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
+clean-noinstLIBRARIES:
+	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
 
-distclean-libLIBRARIES:
+distclean-noinstLIBRARIES:
 
-maintainer-clean-libLIBRARIES:
+maintainer-clean-noinstLIBRARIES:
 
-install-libLIBRARIES: $(lib_LIBRARIES)
-	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(libdir)
-	@list='$(lib_LIBRARIES)'; for p in $$list; do \
-	  if test -f $$p; then \
-	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
-	    $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
-	  else :; fi; \
-	done
-	@$(POST_INSTALL)
-	@list='$(lib_LIBRARIES)'; for p in $$list; do \
-	  if test -f $$p; then \
-	    echo " $(RANLIB) $(DESTDIR)$(libdir)/$$p"; \
-	    $(RANLIB) $(DESTDIR)$(libdir)/$$p; \
-	  else :; fi; \
-	done
-
-uninstall-libLIBRARIES:
-	@$(NORMAL_UNINSTALL)
-	list='$(lib_LIBRARIES)'; for p in $$list; do \
-	  rm -f $(DESTDIR)$(libdir)/$$p; \
-	done
+.c.o:
+	$(COMPILE) -c $<
 
 # FIXME: We should only use cygpath when building on Windows,
 # and only if it is available.
@@ -213,6 +202,9 @@ distclean-compile:
 
 maintainer-clean-compile:
 
+.c.lo:
+	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
+
 .s.lo:
 	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
 
@@ -234,14 +226,14 @@ libnetwork.a: $(libnetwork_a_OBJECTS) $(libnetwork_a_DEPENDENCIES)
 	$(AR) cru libnetwork.a $(libnetwork_a_OBJECTS) $(libnetwork_a_LIBADD)
 	$(RANLIB) libnetwork.a
 
-mostlyclean-noinstPROGRAMS:
+mostlyclean-checkPROGRAMS:
 
-clean-noinstPROGRAMS:
-	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
 
-distclean-noinstPROGRAMS:
+distclean-checkPROGRAMS:
 
-maintainer-clean-noinstPROGRAMS:
+maintainer-clean-checkPROGRAMS:
 
 nettest$(EXEEXT): $(nettest_OBJECTS) $(nettest_DEPENDENCIES)
 	@rm -f nettest$(EXEEXT)
@@ -252,21 +244,6 @@ nettest$(EXEEXT): $(nettest_OBJECTS) $(nettest_DEPENDENCIES)
 	$(CXXCOMPILE) -c `cygpath -w $<`
 .cpp.lo:
 	$(LTCXXCOMPILE) -c $<
-
-install-includeHEADERS: $(include_HEADERS)
-	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(includedir)
-	@list='$(include_HEADERS)'; for p in $$list; do \
-	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
-	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(includedir)/$$p"; \
-	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(includedir)/$$p; \
-	done
-
-uninstall-includeHEADERS:
-	@$(NORMAL_UNINSTALL)
-	list='$(include_HEADERS)'; for p in $$list; do \
-	  rm -f $(DESTDIR)$(includedir)/$$p; \
-	done
 
 tags: TAGS
 
@@ -299,14 +276,9 @@ maintainer-clean-tags:
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
 
-subdir = src/net
+subdir = base/src/net
 
 distdir: $(DISTFILES)
-	here=`cd $(top_builddir) && pwd`; \
-	top_distdir=`cd $(top_distdir) && pwd`; \
-	distdir=`cd $(distdir) && pwd`; \
-	cd $(top_srcdir) \
-	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu src/net/Makefile
 	@for file in $(DISTFILES); do \
 	  d=$(srcdir); \
 	  if test -d $$d/$$file; then \
@@ -317,82 +289,85 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+domainclientsocket.o: domainclientsocket.cpp domainclientsocket.h \
+	iclientsocket.h sotimeout.h ../../../config.h netexceptions.h \
+	socketutils.h fdsocket.h isocket.h isender.h ../utils/buffer.h
+domainserversocket.o: domainserversocket.cpp domainserversocket.h \
+	iserversocket.h sotimeout.h ../../../config.h netexceptions.h \
+	socketutils.h fdsocket.h isocket.h isender.h ../utils/buffer.h
+fdsocket.o: fdsocket.cpp fdsocket.h isocket.h netexceptions.h isender.h \
+	sotimeout.h ../../../config.h socketutils.h ../utils/buffer.h
+isocket.o: isocket.cpp isocket.h netexceptions.h isender.h sotimeout.h
+netexceptions.o: netexceptions.cpp netexceptions.h
+protocol.o: protocol.cpp protocol.h idatalistener.h isender.h \
+	../utils/buffer.h ../../../util/include/basic_types.h \
+	../../../config.h ../../../util/include/minmax.h
+socketadaptor.o: socketadaptor.cpp socketadaptor.h isocket.h \
+	netexceptions.h isender.h sotimeout.h idatalistener.h \
+	../utils/buffer.h
+socketutils.o: socketutils.cpp socketutils.h ../../../config.h \
+	netexceptions.h
+sotimeout.o: sotimeout.cpp sotimeout.h
+tagutils.o: tagutils.cpp tagutils.h ../../../util/include/basic_types.h \
+	../utils/buffer.h
+tcpclientsocket.o: tcpclientsocket.cpp tcpclientsocket.h iclientsocket.h \
+	sotimeout.h ../../../config.h netexceptions.h socketutils.h \
+	fdsocket.h isocket.h isender.h ../utils/buffer.h
+tcpserversocket.o: tcpserversocket.cpp tcpserversocket.h iserversocket.h \
+	sotimeout.h ../../../config.h netexceptions.h socketutils.h \
+	fdsocket.h isocket.h isender.h ../utils/buffer.h
 
-DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-
--include $(DEP_FILES)
-
-mostlyclean-depend:
-
-clean-depend:
-
-distclean-depend:
-	-rm -rf .deps
-
-maintainer-clean-depend:
-
-%.o: %.c
-	@echo '$(COMPILE) -c $<'; \
-	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.c
-	@echo '$(LTCOMPILE) -c $<'; \
-	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
-
-%.o: %.cpp
-	@echo '$(CXXCOMPILE) -c $<'; \
-	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.cpp
-	@echo '$(LTCXXCOMPILE) -c $<'; \
-	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
-install-exec-am: install-libLIBRARIES
+install-exec-am:
 install-exec: install-exec-am
 
-install-data-am: install-includeHEADERS
+install-data-am:
 install-data: install-data-am
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
 install: install-am
-uninstall-am: uninstall-libLIBRARIES uninstall-includeHEADERS
+uninstall-am:
 uninstall: uninstall-am
-all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(HEADERS)
+all-am: Makefile $(LIBRARIES) $(HEADERS)
 all-redirect: all-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
 installdirs:
-	$(mkinstalldirs)  $(DESTDIR)$(libdir) $(DESTDIR)$(includedir)
 
 
 mostlyclean-generic:
@@ -404,52 +379,47 @@ distclean-generic:
 	-rm -f config.cache config.log stamp-h stamp-h[0-9]*
 
 maintainer-clean-generic:
-mostlyclean-am:  mostlyclean-libLIBRARIES mostlyclean-compile \
-		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
+		mostlyclean-libtool mostlyclean-checkPROGRAMS \
+		mostlyclean-tags mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
-clean-am:  clean-libLIBRARIES clean-compile clean-libtool \
-		clean-noinstPROGRAMS clean-tags clean-depend \
-		clean-generic mostlyclean-am
+clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
+		clean-checkPROGRAMS clean-tags clean-generic \
+		mostlyclean-am
 
 clean: clean-am
 
-distclean-am:  distclean-libLIBRARIES distclean-compile \
-		distclean-libtool distclean-noinstPROGRAMS \
-		distclean-tags distclean-depend distclean-generic \
-		clean-am
+distclean-am:  distclean-noinstLIBRARIES distclean-compile \
+		distclean-libtool distclean-checkPROGRAMS \
+		distclean-tags distclean-generic clean-am
 	-rm -f libtool
 
 distclean: distclean-am
 
-maintainer-clean-am:  maintainer-clean-libLIBRARIES \
+maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
 		maintainer-clean-compile maintainer-clean-libtool \
-		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
-		maintainer-clean-depend maintainer-clean-generic \
-		distclean-am
+		maintainer-clean-checkPROGRAMS maintainer-clean-tags \
+		maintainer-clean-generic distclean-am
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
 maintainer-clean: maintainer-clean-am
 
-.PHONY: mostlyclean-libLIBRARIES distclean-libLIBRARIES \
-clean-libLIBRARIES maintainer-clean-libLIBRARIES uninstall-libLIBRARIES \
-install-libLIBRARIES mostlyclean-compile distclean-compile \
-clean-compile maintainer-clean-compile mostlyclean-libtool \
-distclean-libtool clean-libtool maintainer-clean-libtool \
-mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
-clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
-uninstall-includeHEADERS install-includeHEADERS tags mostlyclean-tags \
-distclean-tags clean-tags maintainer-clean-tags distdir \
-mostlyclean-depend distclean-depend clean-depend \
-maintainer-clean-depend info-am info dvi-am dvi check check-am \
-installcheck-am installcheck install-exec-am install-exec \
-install-data-am install-data install-am install uninstall-am uninstall \
-all-redirect all-am all installdirs mostlyclean-generic \
-distclean-generic clean-generic maintainer-clean-generic clean \
-mostlyclean distclean maintainer-clean
+.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
+clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
+mostlyclean-compile distclean-compile clean-compile \
+maintainer-clean-compile mostlyclean-libtool distclean-libtool \
+clean-libtool maintainer-clean-libtool mostlyclean-checkPROGRAMS \
+distclean-checkPROGRAMS clean-checkPROGRAMS \
+maintainer-clean-checkPROGRAMS tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
+dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
+install-exec install-data-am install-data install-am install \
+uninstall-am uninstall all-redirect all-am all installdirs \
+mostlyclean-generic distclean-generic clean-generic \
+maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
diff --git a/base/src/thread/Makefile.in b/base/src/thread/Makefile.in
--- a/base/src/thread/Makefile.in
+++ b/base/src/thread/Makefile.in
@@ -38,7 +38,7 @@ pkgdatadir = $(datadir)/@PACKAGE@
 pkglibdir = $(libdir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
 
-top_builddir = ../..
+top_builddir = ../../..
 
 ACLOCAL = @ACLOCAL@
 AUTOCONF = @AUTOCONF@
@@ -60,51 +60,67 @@ POST_UNINSTALL = :
 host_alias = @host_alias@
 host_triplet = @host@
 AS = @AS@
+AVIFILE_CONFIG = @AVIFILE_CONFIG@
+AVIFILE_CXXFLAGS = @AVIFILE_CXXFLAGS@
+AVIFILE_LDFLAGS = @AVIFILE_LDFLAGS@
 CC = @CC@
 CXX = @CXX@
 DLLTOOL = @DLLTOOL@
 ECHO = @ECHO@
+EFFECTV_SRC_DIR = @EFFECTV_SRC_DIR@
 EXEEXT = @EXEEXT@
+LEX = @LEX@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
 MAKEINFO = @MAKEINFO@
+MOC = @MOC@
 OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
 PACKAGE = @PACKAGE@
-PYTHON = @PYTHON@
+QT_CXXFLAGS = @QT_CXXFLAGS@
+QT_LIBS = @QT_LIBS@
 RANLIB = @RANLIB@
+SDL_CFLAGS = @SDL_CFLAGS@
+SDL_CONFIG = @SDL_CONFIG@
+SDL_LIBS = @SDL_LIBS@
 STRIP = @STRIP@
+UIC = @UIC@
 VERSION = @VERSION@
+YACC = @YACC@
 
 noinst_LIBRARIES = libthread.a
 libthread_a_SOURCES = ithread.cpp imutex.cpp threadposix.cpp ithread.h imutex.h irunnable.h ithreadutil.h thread.h threadposix.h
 
-INCLUDES = -I ..
+INCLUDES = -I @srcdir@/..
 
-noinst_PROGRAMS = threadtest
+TESTS = threadtest
+
+check_PROGRAMS = threadtest
 
 threadtest_SOURCES = testmain.cpp threadtest.cpp  threadtest.h 
 
-threadtest_LDADD = ../TestFramework/libtestframework.la libthread.a -lpthread
+threadtest_LDADD = ../TestFramework/libtestframework.a libthread.a -lpthread
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-CONFIG_HEADER = ../../config.h
+CONFIG_HEADER = ../../../config.h
 CONFIG_CLEAN_FILES = 
 LIBRARIES =  $(noinst_LIBRARIES)
 
 
-DEFS = @DEFS@ -I. -I$(srcdir) -I../..
+DEFS = @DEFS@ -I. -I$(srcdir) -I../../..
 CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
+X_CFLAGS = @X_CFLAGS@
+X_LIBS = @X_LIBS@
+X_EXTRA_LIBS = @X_EXTRA_LIBS@
+X_PRE_LIBS = @X_PRE_LIBS@
 libthread_a_LIBADD = 
 libthread_a_OBJECTS =  ithread.$(OBJEXT) imutex.$(OBJEXT) \
 threadposix.$(OBJEXT)
 AR = ar
-noinst_PROGRAMS =  threadtest$(EXEEXT)
-PROGRAMS =  $(noinst_PROGRAMS)
-
+check_PROGRAMS =  threadtest$(EXEEXT)
 threadtest_OBJECTS =  testmain.$(OBJEXT) threadtest.$(OBJEXT)
-threadtest_DEPENDENCIES =  ../TestFramework/libtestframework.la \
+threadtest_DEPENDENCIES =  ../TestFramework/libtestframework.a \
 libthread.a
 threadtest_LDFLAGS = 
 CXXFLAGS = @CXXFLAGS@
@@ -124,8 +140,6 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-DEP_FILES =  .deps/imutex.P .deps/ithread.P .deps/testmain.P \
-.deps/threadposix.P .deps/threadtest.P
 SOURCES = $(libthread_a_SOURCES) $(threadtest_SOURCES)
 OBJECTS = $(libthread_a_OBJECTS) $(threadtest_OBJECTS)
 
@@ -133,9 +147,9 @@ all: all-redirect
 .SUFFIXES:
 .SUFFIXES: .S .c .cpp .lo .o .obj .s
 $(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
-	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/thread/Makefile
+	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps base/src/thread/Makefile
 
-Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
@@ -148,6 +162,9 @@ clean-noinstLIBRARIES:
 distclean-noinstLIBRARIES:
 
 maintainer-clean-noinstLIBRARIES:
+
+.c.o:
+	$(COMPILE) -c $<
 
 # FIXME: We should only use cygpath when building on Windows,
 # and only if it is available.
@@ -171,6 +188,9 @@ distclean-compile:
 
 maintainer-clean-compile:
 
+.c.lo:
+	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
+
 .s.lo:
 	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
 
@@ -192,14 +212,14 @@ libthread.a: $(libthread_a_OBJECTS) $(libthread_a_DEPENDENCIES)
 	$(AR) cru libthread.a $(libthread_a_OBJECTS) $(libthread_a_LIBADD)
 	$(RANLIB) libthread.a
 
-mostlyclean-noinstPROGRAMS:
+mostlyclean-checkPROGRAMS:
 
-clean-noinstPROGRAMS:
-	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
 
-distclean-noinstPROGRAMS:
+distclean-checkPROGRAMS:
 
-maintainer-clean-noinstPROGRAMS:
+maintainer-clean-checkPROGRAMS:
 
 threadtest$(EXEEXT): $(threadtest_OBJECTS) $(threadtest_DEPENDENCIES)
 	@rm -f threadtest$(EXEEXT)
@@ -242,14 +262,9 @@ maintainer-clean-tags:
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
 
-subdir = src/thread
+subdir = base/src/thread
 
 distdir: $(DISTFILES)
-	here=`cd $(top_builddir) && pwd`; \
-	top_distdir=`cd $(top_distdir) && pwd`; \
-	distdir=`cd $(distdir) && pwd`; \
-	cd $(top_srcdir) \
-	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu src/thread/Makefile
 	@for file in $(DISTFILES); do \
 	  d=$(srcdir); \
 	  if test -d $$d/$$file; then \
@@ -260,62 +275,43 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+imutex.o: imutex.cpp imutex.h
+ithread.o: ithread.cpp ithread.h
+threadposix.o: threadposix.cpp threadposix.h ithread.h imutex.h \
+	ithreadutil.h irunnable.h
 
-DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-
--include $(DEP_FILES)
-
-mostlyclean-depend:
-
-clean-depend:
-
-distclean-depend:
-	-rm -rf .deps
-
-maintainer-clean-depend:
-
-%.o: %.c
-	@echo '$(COMPILE) -c $<'; \
-	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.c
-	@echo '$(LTCOMPILE) -c $<'; \
-	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
-
-%.o: %.cpp
-	@echo '$(CXXCOMPILE) -c $<'; \
-	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.cpp
-	@echo '$(LTCXXCOMPILE) -c $<'; \
-	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -330,7 +326,7 @@ install-am: all-am
 install: install-am
 uninstall-am:
 uninstall: uninstall-am
-all-am: Makefile $(LIBRARIES) $(PROGRAMS)
+all-am: Makefile $(LIBRARIES)
 all-redirect: all-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
@@ -347,30 +343,28 @@ distclean-generic:
 
 maintainer-clean-generic:
 mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
-		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+		mostlyclean-libtool mostlyclean-checkPROGRAMS \
+		mostlyclean-tags mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
 clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
-		clean-noinstPROGRAMS clean-tags clean-depend \
-		clean-generic mostlyclean-am
+		clean-checkPROGRAMS clean-tags clean-generic \
+		mostlyclean-am
 
 clean: clean-am
 
 distclean-am:  distclean-noinstLIBRARIES distclean-compile \
-		distclean-libtool distclean-noinstPROGRAMS \
-		distclean-tags distclean-depend distclean-generic \
-		clean-am
+		distclean-libtool distclean-checkPROGRAMS \
+		distclean-tags distclean-generic clean-am
 	-rm -f libtool
 
 distclean: distclean-am
 
 maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
 		maintainer-clean-compile maintainer-clean-libtool \
-		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
-		maintainer-clean-depend maintainer-clean-generic \
-		distclean-am
+		maintainer-clean-checkPROGRAMS maintainer-clean-tags \
+		maintainer-clean-generic distclean-am
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
@@ -380,11 +374,10 @@ maintainer-clean: maintainer-clean-am
 clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
 mostlyclean-compile distclean-compile clean-compile \
 maintainer-clean-compile mostlyclean-libtool distclean-libtool \
-clean-libtool maintainer-clean-libtool mostlyclean-noinstPROGRAMS \
-distclean-noinstPROGRAMS clean-noinstPROGRAMS \
-maintainer-clean-noinstPROGRAMS tags mostlyclean-tags distclean-tags \
-clean-tags maintainer-clean-tags distdir mostlyclean-depend \
-distclean-depend clean-depend maintainer-clean-depend info-am info \
+clean-libtool maintainer-clean-libtool mostlyclean-checkPROGRAMS \
+distclean-checkPROGRAMS clean-checkPROGRAMS \
+maintainer-clean-checkPROGRAMS tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
 dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
 install-exec install-data-am install-data install-am install \
 uninstall-am uninstall all-redirect all-am all installdirs \
diff --git a/base/src/utils/Makefile.in b/base/src/utils/Makefile.in
--- a/base/src/utils/Makefile.in
+++ b/base/src/utils/Makefile.in
@@ -26,8 +26,10 @@ datadir = @datadir@
 sysconfdir = @sysconfdir@
 sharedstatedir = @sharedstatedir@
 localstatedir = @localstatedir@
+libdir = @libdir@
 infodir = @infodir@
 mandir = @mandir@
+includedir = @includedir@
 oldincludedir = /usr/include
 
 DESTDIR =
@@ -36,7 +38,7 @@ pkgdatadir = $(datadir)/@PACKAGE@
 pkglibdir = $(libdir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
 
-top_builddir = ../..
+top_builddir = ../../..
 
 ACLOCAL = @ACLOCAL@
 AUTOCONF = @AUTOCONF@
@@ -58,52 +60,73 @@ POST_UNINSTALL = :
 host_alias = @host_alias@
 host_triplet = @host@
 AS = @AS@
+AVIFILE_CONFIG = @AVIFILE_CONFIG@
+AVIFILE_CXXFLAGS = @AVIFILE_CXXFLAGS@
+AVIFILE_LDFLAGS = @AVIFILE_LDFLAGS@
 CC = @CC@
 CXX = @CXX@
 DLLTOOL = @DLLTOOL@
 ECHO = @ECHO@
+EFFECTV_SRC_DIR = @EFFECTV_SRC_DIR@
 EXEEXT = @EXEEXT@
+LEX = @LEX@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
 MAKEINFO = @MAKEINFO@
+MOC = @MOC@
 OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
 PACKAGE = @PACKAGE@
-PYTHON = @PYTHON@
+QT_CXXFLAGS = @QT_CXXFLAGS@
+QT_LIBS = @QT_LIBS@
 RANLIB = @RANLIB@
+SDL_CFLAGS = @SDL_CFLAGS@
+SDL_CONFIG = @SDL_CONFIG@
+SDL_LIBS = @SDL_LIBS@
 STRIP = @STRIP@
+UIC = @UIC@
 VERSION = @VERSION@
+YACC = @YACC@
 
-baseincludedir = @includedir@/gephex
-includedir = @includedir@/gephex/utils
-libdir = @libdir@/gephex
+TESTS = utilstest
 
-noinst_PROGRAMS = utilstest
+check_PROGRAMS = utilstest
 
-lib_LIBRARIES = libutils.a
+noinst_LIBRARIES = libutils.a
 
 libutils_a_SOURCES =  		stringtokenizer.cpp 		structscanner.cpp 		filesystem.cpp 		structreader.cpp 		buffer.cpp 		itokenizer.cpp 		streamtokenizer.cpp 		bufferutils.cpp 		xmlutils.cpp 		streamlogger.cpp 		outbytestream.cpp 		inbytestream.cpp 		outbytestreamutils.cpp 		inbytestreamutils.cpp 		bufferstream.cpp 		string_.cpp 		sharedlibrary.cpp 		timing.cpp
 
 
-include_HEADERS =  		autoptr.h 		buffer.h 		bufferutils.h 		filesystem.h 		ilogger.h 		istructtokenlistener.h 		itokenizer.h 		streamlogger.h 		streamtokenizer.h 		stringtokenizer.h 		structreader.h 		structscanner.h 		xmlutils.h 		outbytestream.h 		inbytestream.h 		outbytestreamutils.h 		inbytestreamutils.h 		bufferstream.h 		block.h 		string_.h 		sharedlibrary.h 		timing.h
+noinst_HEADERS =  		autoptr.h 		buffer.h 		bufferutils.h 		filesystem.h 		ilogger.h 		istructtokenlistener.h 		itokenizer.h 		streamlogger.h 		streamtokenizer.h 		stringtokenizer.h 		structreader.h 		structscanner.h 		xmlutils.h 		outbytestream.h 		inbytestream.h 		outbytestreamutils.h 		inbytestreamutils.h 		bufferstream.h 		block.h 		string_.h 		sharedlibrary.h 		timing.h
 
 
-INCLUDES = -I .. #-I $(baseincludedir) 
-
-utilstest_SOURCES =  		testmain.cpp 		stringtokenizertest.cpp 		structreadertest.cpp 		streamtokenizertest.cpp 		structscannertest.cpp 		buffertest.cpp 		filesystemtest.cpp 	        autoptrtest.cpp 	        bytestreamtest.cpp 		bufferstreamtest.cpp 		sharedlibrarytest.cpp 		autoptrtest.h 		bufferstreamtest.h 		buffertest.h 		bytestreamtest.h 		filesystemtest.h 		streamtokenizertest.h 		stringtokenizertest.h 		structreadertest.h 		structscannertest.h 		sharedlibrarytest.h
+INCLUDES =  	-I @srcdir@/.. 	-I@top_srcdir@/util/include 	-I@top_builddir@/util/include
 
 
-utilstest_LDADD = ../TestFramework/libtestframework.la libutils.a -ldl
+utilstest_SOURCES =  	testmain.cpp 	stringtokenizertest.cpp 	structreadertest.cpp 	streamtokenizertest.cpp 	structscannertest.cpp 	buffertest.cpp 	filesystemtest.cpp         autoptrtest.cpp         bytestreamtest.cpp 	bufferstreamtest.cpp 	sharedlibrarytest.cpp 	autoptrtest.h 	bufferstreamtest.h 	buffertest.h 	bytestreamtest.h 	filesystemtest.h 	streamtokenizertest.h 	stringtokenizertest.h 	structreadertest.h 	structscannertest.h 	sharedlibrarytest.h
+
+
+@NEED_DL_TRUE@LIB_DL_FLAGS = -ldl
+
+utilstest_LDADD =  	-L@builddir@/../TestFramework 	-L@builddir@         -ltestframework 	-lutils $(LIB_DL_FLAGS)
+
+
+utilstest_DEPENDENCIES =  	@builddir@/../TestFramework/libtestframework.a 	@builddir@/libutils.a
+
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-CONFIG_HEADER = ../../config.h
+CONFIG_HEADER = ../../../config.h
 CONFIG_CLEAN_FILES = 
-LIBRARIES =  $(lib_LIBRARIES)
+LIBRARIES =  $(noinst_LIBRARIES)
 
 
-DEFS = @DEFS@ -I. -I$(srcdir) -I../..
+DEFS = @DEFS@ -I. -I$(srcdir) -I../../..
 CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
+X_CFLAGS = @X_CFLAGS@
+X_LIBS = @X_LIBS@
+X_EXTRA_LIBS = @X_EXTRA_LIBS@
+X_PRE_LIBS = @X_PRE_LIBS@
 libutils_a_LIBADD = 
 libutils_a_OBJECTS =  stringtokenizer.$(OBJEXT) structscanner.$(OBJEXT) \
 filesystem.$(OBJEXT) structreader.$(OBJEXT) buffer.$(OBJEXT) \
@@ -113,16 +136,12 @@ inbytestream.$(OBJEXT) outbytestreamutils.$(OBJEXT) \
 inbytestreamutils.$(OBJEXT) bufferstream.$(OBJEXT) string_.$(OBJEXT) \
 sharedlibrary.$(OBJEXT) timing.$(OBJEXT)
 AR = ar
-noinst_PROGRAMS =  utilstest$(EXEEXT)
-PROGRAMS =  $(noinst_PROGRAMS)
-
+check_PROGRAMS =  utilstest$(EXEEXT)
 utilstest_OBJECTS =  testmain.$(OBJEXT) stringtokenizertest.$(OBJEXT) \
 structreadertest.$(OBJEXT) streamtokenizertest.$(OBJEXT) \
 structscannertest.$(OBJEXT) buffertest.$(OBJEXT) \
 filesystemtest.$(OBJEXT) autoptrtest.$(OBJEXT) bytestreamtest.$(OBJEXT) \
 bufferstreamtest.$(OBJEXT) sharedlibrarytest.$(OBJEXT)
-utilstest_DEPENDENCIES =  ../TestFramework/libtestframework.la \
-libutils.a
 utilstest_LDFLAGS = 
 CXXFLAGS = @CXXFLAGS@
 CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
@@ -134,7 +153,7 @@ COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CF
 LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 CCLD = $(CC)
 LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
-HEADERS =  $(include_HEADERS)
+HEADERS =  $(noinst_HEADERS)
 
 DIST_COMMON =  Makefile.am Makefile.in
 
@@ -143,17 +162,6 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-DEP_FILES =  .deps/autoptrtest.P .deps/buffer.P .deps/bufferstream.P \
-.deps/bufferstreamtest.P .deps/buffertest.P .deps/bufferutils.P \
-.deps/bytestreamtest.P .deps/filesystem.P .deps/filesystemtest.P \
-.deps/inbytestream.P .deps/inbytestreamutils.P .deps/itokenizer.P \
-.deps/outbytestream.P .deps/outbytestreamutils.P .deps/sharedlibrary.P \
-.deps/sharedlibrarytest.P .deps/streamlogger.P .deps/streamtokenizer.P \
-.deps/streamtokenizertest.P .deps/string_.P .deps/stringtokenizer.P \
-.deps/stringtokenizertest.P .deps/structreader.P \
-.deps/structreadertest.P .deps/structscanner.P \
-.deps/structscannertest.P .deps/testmain.P .deps/timing.P \
-.deps/xmlutils.P
 SOURCES = $(libutils_a_SOURCES) $(utilstest_SOURCES)
 OBJECTS = $(libutils_a_OBJECTS) $(utilstest_OBJECTS)
 
@@ -161,44 +169,24 @@ all: all-redirect
 .SUFFIXES:
 .SUFFIXES: .S .c .cpp .lo .o .obj .s
 $(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
-	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/utils/Makefile
+	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps base/src/utils/Makefile
 
-Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
 
-mostlyclean-libLIBRARIES:
+mostlyclean-noinstLIBRARIES:
 
-clean-libLIBRARIES:
-	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
+clean-noinstLIBRARIES:
+	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
 
-distclean-libLIBRARIES:
+distclean-noinstLIBRARIES:
 
-maintainer-clean-libLIBRARIES:
+maintainer-clean-noinstLIBRARIES:
 
-install-libLIBRARIES: $(lib_LIBRARIES)
-	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(libdir)
-	@list='$(lib_LIBRARIES)'; for p in $$list; do \
-	  if test -f $$p; then \
-	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
-	    $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
-	  else :; fi; \
-	done
-	@$(POST_INSTALL)
-	@list='$(lib_LIBRARIES)'; for p in $$list; do \
-	  if test -f $$p; then \
-	    echo " $(RANLIB) $(DESTDIR)$(libdir)/$$p"; \
-	    $(RANLIB) $(DESTDIR)$(libdir)/$$p; \
-	  else :; fi; \
-	done
-
-uninstall-libLIBRARIES:
-	@$(NORMAL_UNINSTALL)
-	list='$(lib_LIBRARIES)'; for p in $$list; do \
-	  rm -f $(DESTDIR)$(libdir)/$$p; \
-	done
+.c.o:
+	$(COMPILE) -c $<
 
 # FIXME: We should only use cygpath when building on Windows,
 # and only if it is available.
@@ -222,6 +210,9 @@ distclean-compile:
 
 maintainer-clean-compile:
 
+.c.lo:
+	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
+
 .s.lo:
 	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
 
@@ -243,14 +234,14 @@ libutils.a: $(libutils_a_OBJECTS) $(libutils_a_DEPENDENCIES)
 	$(AR) cru libutils.a $(libutils_a_OBJECTS) $(libutils_a_LIBADD)
 	$(RANLIB) libutils.a
 
-mostlyclean-noinstPROGRAMS:
+mostlyclean-checkPROGRAMS:
 
-clean-noinstPROGRAMS:
-	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
 
-distclean-noinstPROGRAMS:
+distclean-checkPROGRAMS:
 
-maintainer-clean-noinstPROGRAMS:
+maintainer-clean-checkPROGRAMS:
 
 utilstest$(EXEEXT): $(utilstest_OBJECTS) $(utilstest_DEPENDENCIES)
 	@rm -f utilstest$(EXEEXT)
@@ -261,21 +252,6 @@ utilstest$(EXEEXT): $(utilstest_OBJECTS) $(utilstest_DEPENDENCIES)
 	$(CXXCOMPILE) -c `cygpath -w $<`
 .cpp.lo:
 	$(LTCXXCOMPILE) -c $<
-
-install-includeHEADERS: $(include_HEADERS)
-	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(includedir)
-	@list='$(include_HEADERS)'; for p in $$list; do \
-	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
-	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(includedir)/$$p"; \
-	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(includedir)/$$p; \
-	done
-
-uninstall-includeHEADERS:
-	@$(NORMAL_UNINSTALL)
-	list='$(include_HEADERS)'; for p in $$list; do \
-	  rm -f $(DESTDIR)$(includedir)/$$p; \
-	done
 
 tags: TAGS
 
@@ -308,14 +284,9 @@ maintainer-clean-tags:
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
 
-subdir = src/utils
+subdir = base/src/utils
 
 distdir: $(DISTFILES)
-	here=`cd $(top_builddir) && pwd`; \
-	top_distdir=`cd $(top_distdir) && pwd`; \
-	distdir=`cd $(distdir) && pwd`; \
-	cd $(top_srcdir) \
-	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu src/utils/Makefile
 	@for file in $(DISTFILES); do \
 	  d=$(srcdir); \
 	  if test -d $$d/$$file; then \
@@ -326,82 +297,80 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+buffer.o: buffer.cpp buffer.h ../../../util/include/minmax.h
+bufferstream.o: bufferstream.cpp bufferstream.h buffer.h
+bufferutils.o: bufferutils.cpp bufferutils.h buffer.h xmlutils.h
+filesystem.o: filesystem.cpp filesystem.h ../../../config.h
+inbytestream.o: inbytestream.cpp inbytestream.h buffer.h
+inbytestreamutils.o: inbytestreamutils.cpp inbytestreamutils.h \
+	inbytestream.h buffer.h
+itokenizer.o: itokenizer.cpp itokenizer.h
+outbytestream.o: outbytestream.cpp outbytestream.h buffer.h
+outbytestreamutils.o: outbytestreamutils.cpp outbytestreamutils.h \
+	outbytestream.h buffer.h
+sharedlibrary.o: sharedlibrary.cpp sharedlibrary.h ../../../config.h
+streamlogger.o: streamlogger.cpp streamlogger.h ilogger.h
+streamtokenizer.o: streamtokenizer.cpp streamtokenizer.h itokenizer.h
+string_.o: string_.cpp string_.h xmlutils.h
+stringtokenizer.o: stringtokenizer.cpp stringtokenizer.h itokenizer.h
+structreader.o: structreader.cpp structreader.h istructtokenlistener.h \
+	structscanner.h
+structscanner.o: structscanner.cpp structscanner.h \
+	istructtokenlistener.h stringtokenizer.h itokenizer.h
+timing.o: timing.cpp timing.h ../../../config.h
+xmlutils.o: xmlutils.cpp xmlutils.h
 
-DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-
--include $(DEP_FILES)
-
-mostlyclean-depend:
-
-clean-depend:
-
-distclean-depend:
-	-rm -rf .deps
-
-maintainer-clean-depend:
-
-%.o: %.c
-	@echo '$(COMPILE) -c $<'; \
-	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.c
-	@echo '$(LTCOMPILE) -c $<'; \
-	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
-
-%.o: %.cpp
-	@echo '$(CXXCOMPILE) -c $<'; \
-	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.cpp
-	@echo '$(LTCXXCOMPILE) -c $<'; \
-	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
-install-exec-am: install-libLIBRARIES
+install-exec-am:
 install-exec: install-exec-am
 
-install-data-am: install-includeHEADERS
+install-data-am:
 install-data: install-data-am
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
 install: install-am
-uninstall-am: uninstall-libLIBRARIES uninstall-includeHEADERS
+uninstall-am:
 uninstall: uninstall-am
-all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(HEADERS)
+all-am: Makefile $(LIBRARIES) $(HEADERS)
 all-redirect: all-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
 installdirs:
-	$(mkinstalldirs)  $(DESTDIR)$(libdir) $(DESTDIR)$(includedir)
 
 
 mostlyclean-generic:
@@ -413,52 +382,47 @@ distclean-generic:
 	-rm -f config.cache config.log stamp-h stamp-h[0-9]*
 
 maintainer-clean-generic:
-mostlyclean-am:  mostlyclean-libLIBRARIES mostlyclean-compile \
-		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
+		mostlyclean-libtool mostlyclean-checkPROGRAMS \
+		mostlyclean-tags mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
-clean-am:  clean-libLIBRARIES clean-compile clean-libtool \
-		clean-noinstPROGRAMS clean-tags clean-depend \
-		clean-generic mostlyclean-am
+clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
+		clean-checkPROGRAMS clean-tags clean-generic \
+		mostlyclean-am
 
 clean: clean-am
 
-distclean-am:  distclean-libLIBRARIES distclean-compile \
-		distclean-libtool distclean-noinstPROGRAMS \
-		distclean-tags distclean-depend distclean-generic \
-		clean-am
+distclean-am:  distclean-noinstLIBRARIES distclean-compile \
+		distclean-libtool distclean-checkPROGRAMS \
+		distclean-tags distclean-generic clean-am
 	-rm -f libtool
 
 distclean: distclean-am
 
-maintainer-clean-am:  maintainer-clean-libLIBRARIES \
+maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
 		maintainer-clean-compile maintainer-clean-libtool \
-		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
-		maintainer-clean-depend maintainer-clean-generic \
-		distclean-am
+		maintainer-clean-checkPROGRAMS maintainer-clean-tags \
+		maintainer-clean-generic distclean-am
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
 maintainer-clean: maintainer-clean-am
 
-.PHONY: mostlyclean-libLIBRARIES distclean-libLIBRARIES \
-clean-libLIBRARIES maintainer-clean-libLIBRARIES uninstall-libLIBRARIES \
-install-libLIBRARIES mostlyclean-compile distclean-compile \
-clean-compile maintainer-clean-compile mostlyclean-libtool \
-distclean-libtool clean-libtool maintainer-clean-libtool \
-mostlyclean-noinstPROGRAMS distclean-noinstPROGRAMS \
-clean-noinstPROGRAMS maintainer-clean-noinstPROGRAMS \
-uninstall-includeHEADERS install-includeHEADERS tags mostlyclean-tags \
-distclean-tags clean-tags maintainer-clean-tags distdir \
-mostlyclean-depend distclean-depend clean-depend \
-maintainer-clean-depend info-am info dvi-am dvi check check-am \
-installcheck-am installcheck install-exec-am install-exec \
-install-data-am install-data install-am install uninstall-am uninstall \
-all-redirect all-am all installdirs mostlyclean-generic \
-distclean-generic clean-generic maintainer-clean-generic clean \
-mostlyclean distclean maintainer-clean
+.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
+clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
+mostlyclean-compile distclean-compile clean-compile \
+maintainer-clean-compile mostlyclean-libtool distclean-libtool \
+clean-libtool maintainer-clean-libtool mostlyclean-checkPROGRAMS \
+distclean-checkPROGRAMS clean-checkPROGRAMS \
+maintainer-clean-checkPROGRAMS tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
+dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
+install-exec install-data-am install-data install-am install \
+uninstall-am uninstall all-redirect all-am all installdirs \
+mostlyclean-generic distclean-generic clean-generic \
+maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
diff --git a/engine/src/model/Makefile.in b/engine/src/model/Makefile.in
--- a/engine/src/model/Makefile.in
+++ b/engine/src/model/Makefile.in
@@ -36,7 +36,7 @@ pkgdatadir = $(datadir)/@PACKAGE@
 pkglibdir = $(libdir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
 
-top_builddir = ../..
+top_builddir = ../../..
 
 ACLOCAL = @ACLOCAL@
 AUTOCONF = @AUTOCONF@
@@ -58,26 +58,40 @@ POST_UNINSTALL = :
 host_alias = @host_alias@
 host_triplet = @host@
 AS = @AS@
+AVIFILE_CONFIG = @AVIFILE_CONFIG@
+AVIFILE_CXXFLAGS = @AVIFILE_CXXFLAGS@
+AVIFILE_LDFLAGS = @AVIFILE_LDFLAGS@
 CC = @CC@
 CXX = @CXX@
 DLLTOOL = @DLLTOOL@
 ECHO = @ECHO@
+EFFECTV_SRC_DIR = @EFFECTV_SRC_DIR@
 EXEEXT = @EXEEXT@
+LEX = @LEX@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
 MAKEINFO = @MAKEINFO@
+MOC = @MOC@
 OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
 PACKAGE = @PACKAGE@
+QT_CXXFLAGS = @QT_CXXFLAGS@
+QT_LIBS = @QT_LIBS@
 RANLIB = @RANLIB@
+SDL_CFLAGS = @SDL_CFLAGS@
+SDL_CONFIG = @SDL_CONFIG@
+SDL_LIBS = @SDL_LIBS@
 STRIP = @STRIP@
+UIC = @UIC@
 VERSION = @VERSION@
+YACC = @YACC@
 
 baseincludedir = @includedir@/gephex
 libdir = @libdir@/gephex
 includedir = $(baseincludedir)/model
 
-INCLUDES = -I.. -I $(baseincludedir)
+INCLUDES =  	-I @srcdir@/.. 	-I @srcdir@/../../../base/src 	-I @builddir@/../../../base/src 	-I @top_srcdir@/util/include 	-I @top_builddir@/util/include
+
 
 noinst_LIBRARIES = libmodel.a
 
@@ -86,20 +100,26 @@ libmodel_a_SOURCES = model.cpp                      model.h                     
 
 noinst_HEADERS = model.h
 
-noinst_PROGRAMS = modeltest
+TESTS = modeltest
+
+check_PROGRAMS = modeltest
 modeltest_SOURCES = testmain.cpp datatreetest.cpp datatreetest.h
-modeltest_LDFLAGS = -L$(libdir)
+modeltest_LDFLAGS = -L$(libdir) -L../../../base/src/TestFramework -L../../../base/src/utils
 modeltest_LDADD = -ltestframework libmodel.a -lutils
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-CONFIG_HEADER = ../../config.h
+CONFIG_HEADER = ../../../config.h
 CONFIG_CLEAN_FILES = 
 LIBRARIES =  $(noinst_LIBRARIES)
 
 
-DEFS = @DEFS@ -I. -I$(srcdir) -I../..
+DEFS = @DEFS@ -I. -I$(srcdir) -I../../..
 CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
+X_CFLAGS = @X_CFLAGS@
+X_LIBS = @X_LIBS@
+X_EXTRA_LIBS = @X_EXTRA_LIBS@
+X_PRE_LIBS = @X_PRE_LIBS@
 libmodel_a_LIBADD = 
 libmodel_a_OBJECTS =  model.$(OBJEXT) graph.$(OBJEXT) \
 graphnode.$(OBJEXT) graphconnection.$(OBJEXT) \
@@ -107,9 +127,7 @@ controllvalueset.$(OBJEXT) datatree.$(OBJEXT) persistentinode.$(OBJEXT) \
 standardinode.$(OBJEXT) debugpersistor.$(OBJEXT) \
 graphfilesystem.$(OBJEXT) graphserial.$(OBJEXT)
 AR = ar
-noinst_PROGRAMS =  modeltest$(EXEEXT)
-PROGRAMS =  $(noinst_PROGRAMS)
-
+check_PROGRAMS =  modeltest$(EXEEXT)
 modeltest_OBJECTS =  testmain.$(OBJEXT) datatreetest.$(OBJEXT)
 modeltest_DEPENDENCIES =  libmodel.a
 CXXFLAGS = @CXXFLAGS@
@@ -131,11 +149,6 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-DEP_FILES =  .deps/controllvalueset.P .deps/datatree.P \
-.deps/datatreetest.P .deps/debugpersistor.P .deps/graph.P \
-.deps/graphconnection.P .deps/graphfilesystem.P .deps/graphnode.P \
-.deps/graphserial.P .deps/model.P .deps/persistentinode.P \
-.deps/standardinode.P .deps/testmain.P
 SOURCES = $(libmodel_a_SOURCES) $(modeltest_SOURCES)
 OBJECTS = $(libmodel_a_OBJECTS) $(modeltest_OBJECTS)
 
@@ -143,9 +156,9 @@ all: all-redirect
 .SUFFIXES:
 .SUFFIXES: .S .c .cpp .lo .o .obj .s
 $(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
-	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/model/Makefile
+	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps engine/src/model/Makefile
 
-Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
@@ -158,6 +171,9 @@ clean-noinstLIBRARIES:
 distclean-noinstLIBRARIES:
 
 maintainer-clean-noinstLIBRARIES:
+
+.c.o:
+	$(COMPILE) -c $<
 
 # FIXME: We should only use cygpath when building on Windows,
 # and only if it is available.
@@ -181,6 +197,9 @@ distclean-compile:
 
 maintainer-clean-compile:
 
+.c.lo:
+	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
+
 .s.lo:
 	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
 
@@ -202,14 +221,14 @@ libmodel.a: $(libmodel_a_OBJECTS) $(libmodel_a_DEPENDENCIES)
 	$(AR) cru libmodel.a $(libmodel_a_OBJECTS) $(libmodel_a_LIBADD)
 	$(RANLIB) libmodel.a
 
-mostlyclean-noinstPROGRAMS:
+mostlyclean-checkPROGRAMS:
 
-clean-noinstPROGRAMS:
-	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
 
-distclean-noinstPROGRAMS:
+distclean-checkPROGRAMS:
 
-maintainer-clean-noinstPROGRAMS:
+maintainer-clean-checkPROGRAMS:
 
 modeltest$(EXEEXT): $(modeltest_OBJECTS) $(modeltest_DEPENDENCIES)
 	@rm -f modeltest$(EXEEXT)
@@ -252,14 +271,9 @@ maintainer-clean-tags:
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
 
-subdir = src/model
+subdir = engine/src/model
 
 distdir: $(DISTFILES)
-	here=`cd $(top_builddir) && pwd`; \
-	top_distdir=`cd $(top_distdir) && pwd`; \
-	distdir=`cd $(distdir) && pwd`; \
-	cd $(top_srcdir) \
-	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu src/model/Makefile
 	@for file in $(DISTFILES); do \
 	  d=$(srcdir); \
 	  if test -d $$d/$$file; then \
@@ -270,62 +284,99 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+controllvalueset.o: controllvalueset.cpp controllvalueset.h \
+	../../../base/src/utils/buffer.h
+datatree.o: datatree.cpp datatree.h ../../../base/src/utils/buffer.h \
+	datatreetypes.h idatatreepersistor.h \
+	../../../base/src/utils/bufferutils.h inode.h standardinode.h
+debugpersistor.o: debugpersistor.cpp debugpersistor.h \
+	idatatreepersistor.h datatreetypes.h datatree.h \
+	../../../base/src/utils/buffer.h \
+	../../../base/src/utils/bufferutils.h
+graph.o: graph.cpp graph.h ../../../base/src/utils/autoptr.h \
+	../../../config.h graphconnection.h graphnode.h \
+	../../../base/src/utils/buffer.h \
+	../../../base/src/interfaces/imoduleclassspec.h \
+	controllvalueset.h
+graphconnection.o: graphconnection.cpp graphconnection.h
+graphfilesystem.o: graphfilesystem.cpp graphfilesystem.h \
+	../../../base/src/utils/autoptr.h ../../../config.h specmap.h \
+	../../../base/src/utils/filesystem.h graph.h graphserial.h \
+	controllvalueset.h ../../../base/src/utils/buffer.h
+graphnode.o: graphnode.cpp graphnode.h ../../../base/src/utils/buffer.h \
+	../../../base/src/interfaces/imoduleclassspec.h \
+	../../../base/src/utils/bufferutils.h
+graphserial.o: graphserial.cpp graphserial.h specmap.h \
+	../../../base/src/utils/autoptr.h ../../../config.h \
+	../../../base/src/interfaces/imoduleclassspec.h graph.h \
+	graphnode.h ../../../base/src/utils/buffer.h graphconnection.h \
+	controllvalueset.h ../../../base/src/utils/xmlutils.h \
+	../../../base/src/utils/bufferutils.h
+model.o: model.cpp model.h ../../../base/src/utils/autoptr.h \
+	../../../config.h specmap.h \
+	../../../base/src/interfaces/imoduleconstructiondumbsender.h \
+	../../../base/src/interfaces/imoduleclassspecreceiver.h \
+	../../../base/src/interfaces/igraphnamesender.h \
+	../../../base/src/interfaces/imodelcontrolreceiver.h \
+	../../../base/src/interfaces/imoduleconstructionsmartsender.h \
+	../../../base/src/interfaces/imoduledatasender.h \
+	../../../base/src/interfaces/iserializedgraphsender.h \
+	../../../base/src/interfaces/ismartcontrolvaluereceiver.h \
+	../../../base/src/interfaces/icontrolvaluesender.h \
+	../../../base/src/interfaces/irenderercontrolsender.h \
+	../../../base/src/interfaces/imodulestatisticssender.h \
+	../../../base/src/interfaces/imodulestatisticssmartreceiver.h \
+	../../../base/src/interfaces/imodelstatussender.h graph.h \
+	graphserial.h graphnode.h ../../../base/src/utils/buffer.h \
+	graphconnection.h graphfilesystem.h \
+	../../../base/src/interfaces/igraphnamereceiver.h \
+	../../../base/src/interfaces/imoduleconstructionsmartreceiver.h \
+	../../../base/src/interfaces/imoduleconstructiondumbreceiver.h \
+	../../../base/src/interfaces/imoduledatareceiver.h \
+	../../../base/src/interfaces/iserializedgraphreceiver.h \
+	../../../base/src/interfaces/irenderercontrolreceiver.h \
+	../../../base/src/interfaces/imoduleclassspec.h \
+	../../../base/src/interfaces/icontrolvaluereceiver.h \
+	../../../base/src/interfaces/imodulestatisticsreceiver.h \
+	../../../base/src/interfaces/imodelstatusreceiver.h \
+	controllvalueset.h
+persistentinode.o: persistentinode.cpp persistentinode.h standardinode.h \
+	inode.h datatreetypes.h ../../../base/src/utils/buffer.h
+standardinode.o: standardinode.cpp standardinode.h inode.h \
+	datatreetypes.h ../../../base/src/utils/buffer.h
 
-DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-
--include $(DEP_FILES)
-
-mostlyclean-depend:
-
-clean-depend:
-
-distclean-depend:
-	-rm -rf .deps
-
-maintainer-clean-depend:
-
-%.o: %.c
-	@echo '$(COMPILE) -c $<'; \
-	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.c
-	@echo '$(LTCOMPILE) -c $<'; \
-	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
-
-%.o: %.cpp
-	@echo '$(CXXCOMPILE) -c $<'; \
-	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.cpp
-	@echo '$(LTCXXCOMPILE) -c $<'; \
-	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -340,7 +391,7 @@ install-am: all-am
 install: install-am
 uninstall-am:
 uninstall: uninstall-am
-all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(HEADERS)
+all-am: Makefile $(LIBRARIES) $(HEADERS)
 all-redirect: all-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
@@ -357,30 +408,28 @@ distclean-generic:
 
 maintainer-clean-generic:
 mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
-		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+		mostlyclean-libtool mostlyclean-checkPROGRAMS \
+		mostlyclean-tags mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
 clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
-		clean-noinstPROGRAMS clean-tags clean-depend \
-		clean-generic mostlyclean-am
+		clean-checkPROGRAMS clean-tags clean-generic \
+		mostlyclean-am
 
 clean: clean-am
 
 distclean-am:  distclean-noinstLIBRARIES distclean-compile \
-		distclean-libtool distclean-noinstPROGRAMS \
-		distclean-tags distclean-depend distclean-generic \
-		clean-am
+		distclean-libtool distclean-checkPROGRAMS \
+		distclean-tags distclean-generic clean-am
 	-rm -f libtool
 
 distclean: distclean-am
 
 maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
 		maintainer-clean-compile maintainer-clean-libtool \
-		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
-		maintainer-clean-depend maintainer-clean-generic \
-		distclean-am
+		maintainer-clean-checkPROGRAMS maintainer-clean-tags \
+		maintainer-clean-generic distclean-am
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
@@ -390,11 +439,10 @@ maintainer-clean: maintainer-clean-am
 clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
 mostlyclean-compile distclean-compile clean-compile \
 maintainer-clean-compile mostlyclean-libtool distclean-libtool \
-clean-libtool maintainer-clean-libtool mostlyclean-noinstPROGRAMS \
-distclean-noinstPROGRAMS clean-noinstPROGRAMS \
-maintainer-clean-noinstPROGRAMS tags mostlyclean-tags distclean-tags \
-clean-tags maintainer-clean-tags distdir mostlyclean-depend \
-distclean-depend clean-depend maintainer-clean-depend info-am info \
+clean-libtool maintainer-clean-libtool mostlyclean-checkPROGRAMS \
+distclean-checkPROGRAMS clean-checkPROGRAMS \
+maintainer-clean-checkPROGRAMS tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
 dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
 install-exec install-data-am install-data install-am install \
 uninstall-am uninstall all-redirect all-am all installdirs \
diff --git a/qtgui/src/guimodel/Makefile.in b/qtgui/src/guimodel/Makefile.in
--- a/qtgui/src/guimodel/Makefile.in
+++ b/qtgui/src/guimodel/Makefile.in
@@ -26,8 +26,10 @@ datadir = @datadir@
 sysconfdir = @sysconfdir@
 sharedstatedir = @sharedstatedir@
 localstatedir = @localstatedir@
+libdir = @libdir@
 infodir = @infodir@
 mandir = @mandir@
+includedir = @includedir@
 oldincludedir = /usr/include
 
 DESTDIR =
@@ -36,7 +38,7 @@ pkgdatadir = $(datadir)/@PACKAGE@
 pkglibdir = $(libdir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
 
-top_builddir = ../..
+top_builddir = ../../..
 
 ACLOCAL = @ACLOCAL@
 AUTOCONF = @AUTOCONF@
@@ -58,44 +60,64 @@ POST_UNINSTALL = :
 host_alias = @host_alias@
 host_triplet = @host@
 AS = @AS@
+AVIFILE_CONFIG = @AVIFILE_CONFIG@
+AVIFILE_CXXFLAGS = @AVIFILE_CXXFLAGS@
+AVIFILE_LDFLAGS = @AVIFILE_LDFLAGS@
 CC = @CC@
 CXX = @CXX@
 DLLTOOL = @DLLTOOL@
 ECHO = @ECHO@
+EFFECTV_SRC_DIR = @EFFECTV_SRC_DIR@
 EXEEXT = @EXEEXT@
+LEX = @LEX@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
 MAKEINFO = @MAKEINFO@
+MOC = @MOC@
 OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
 PACKAGE = @PACKAGE@
+QT_CXXFLAGS = @QT_CXXFLAGS@
+QT_LIBS = @QT_LIBS@
 RANLIB = @RANLIB@
+SDL_CFLAGS = @SDL_CFLAGS@
+SDL_CONFIG = @SDL_CONFIG@
+SDL_LIBS = @SDL_LIBS@
 STRIP = @STRIP@
+UIC = @UIC@
 VERSION = @VERSION@
+YACC = @YACC@
 
-baseincludedir = @includedir@/gephex
-includedir = $(baseincludedir)/guimodel
-libdir = @libdir@/gephex
+INCLUDES = -I @srcdir@/../../../base/src 	   -I @builddir@/../../../base/src 	   -I @srcdir@/../../../util/include
 
-INCLUDES = -I $(baseincludedir)
 
 noinst_LIBRARIES = libguimodel.a
-libguimodel_a_SOURCES = controlmodel.cpp moduleinfo.cpp moduleclassmodel.cpp point.cpp graphmodel.cpp xpm.cpp controlvaluedispatcher.cpp moduledatadispatcher.cpp enginewrapper.cpp actionsequencerwrapper.cpp controlmodel.h controlvaluedispatcher.h enginewrapper.h graphmodel.h icontrolconnectview.h  icontrolview.h igraphview.h  imoduleclassview.h moduleclassmodel.h moduledatadispatcher.h moduleinfo.h pluginfo.h point.h xpm.h actionsequencerwrapper.h  iscenesequencer.h iscenechangelistener.h
+libguimodel_a_SOURCES =  	controlmodel.cpp 	moduleinfo.cpp 	moduleclassmodel.cpp 	point.cpp 	graphmodel.cpp 	xpm.cpp 	controlvaluedispatcher.cpp 	moduledatadispatcher.cpp 	enginewrapper.cpp 	actionsequencerwrapper.cpp 	controlmodel.h 	controlvaluedispatcher.h 	enginewrapper.h 	graphmodel.h 	icontrolconnectview.h 	icontrolview.h 	igraphview.h 	imoduleclassview.h 	moduleclassmodel.h 	moduledatadispatcher.h 	moduleinfo.h 	pluginfo.h 	point.h 	xpm.h 	actionsequencerwrapper.h 	iscenesequencer.h 	iscenechangelistener.h
 
-noinst_PROGRAMS = guimodeltest
-guimodeltest_SOURCES = testmain.cpp actionsequencerwrapper.cpp actionsequencerwrappertest.cpp actionsequencerwrappertest.h
 
-guimodeltest_LDADD = -L$(libdir) -ltestframework -lutils
+TESTS = guimodeltest
+
+check_PROGRAMS = guimodeltest
+
+guimodeltest_SOURCES =  	testmain.cpp 	actionsequencerwrapper.cpp 	actionsequencerwrappertest.cpp 	actionsequencerwrappertest.h
+
+
+guimodeltest_LDADD = -L../../../base/src/TestFramework -ltestframework 			-L../../../base/src/utils -lutils
+
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
-CONFIG_HEADER = ../../config.h
+CONFIG_HEADER = ../../../config.h
 CONFIG_CLEAN_FILES = 
 LIBRARIES =  $(noinst_LIBRARIES)
 
 
-DEFS = @DEFS@ -I. -I$(srcdir) -I../..
+DEFS = @DEFS@ -I. -I$(srcdir) -I../../..
 CPPFLAGS = @CPPFLAGS@
 LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
+X_CFLAGS = @X_CFLAGS@
+X_LIBS = @X_LIBS@
+X_EXTRA_LIBS = @X_EXTRA_LIBS@
+X_PRE_LIBS = @X_PRE_LIBS@
 libguimodel_a_LIBADD = 
 libguimodel_a_OBJECTS =  controlmodel.$(OBJEXT) moduleinfo.$(OBJEXT) \
 moduleclassmodel.$(OBJEXT) point.$(OBJEXT) graphmodel.$(OBJEXT) \
@@ -103,9 +125,7 @@ xpm.$(OBJEXT) controlvaluedispatcher.$(OBJEXT) \
 moduledatadispatcher.$(OBJEXT) enginewrapper.$(OBJEXT) \
 actionsequencerwrapper.$(OBJEXT)
 AR = ar
-noinst_PROGRAMS =  guimodeltest$(EXEEXT)
-PROGRAMS =  $(noinst_PROGRAMS)
-
+check_PROGRAMS =  guimodeltest$(EXEEXT)
 guimodeltest_OBJECTS =  testmain.$(OBJEXT) \
 actionsequencerwrapper.$(OBJEXT) actionsequencerwrappertest.$(OBJEXT)
 guimodeltest_DEPENDENCIES = 
@@ -127,11 +147,6 @@ DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-DEP_FILES =  .deps/actionsequencerwrapper.P \
-.deps/actionsequencerwrappertest.P .deps/controlmodel.P \
-.deps/controlvaluedispatcher.P .deps/enginewrapper.P .deps/graphmodel.P \
-.deps/moduleclassmodel.P .deps/moduledatadispatcher.P \
-.deps/moduleinfo.P .deps/point.P .deps/testmain.P .deps/xpm.P
 SOURCES = $(libguimodel_a_SOURCES) $(guimodeltest_SOURCES)
 OBJECTS = $(libguimodel_a_OBJECTS) $(guimodeltest_OBJECTS)
 
@@ -139,9 +154,9 @@ all: all-redirect
 .SUFFIXES:
 .SUFFIXES: .S .c .cpp .lo .o .obj .s
 $(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
-	cd $(top_srcdir) && $(AUTOMAKE) --gnu src/guimodel/Makefile
+	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps qtgui/src/guimodel/Makefile
 
-Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
@@ -154,6 +169,9 @@ clean-noinstLIBRARIES:
 distclean-noinstLIBRARIES:
 
 maintainer-clean-noinstLIBRARIES:
+
+.c.o:
+	$(COMPILE) -c $<
 
 # FIXME: We should only use cygpath when building on Windows,
 # and only if it is available.
@@ -177,6 +195,9 @@ distclean-compile:
 
 maintainer-clean-compile:
 
+.c.lo:
+	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
+
 .s.lo:
 	$(LIBTOOL) --mode=compile $(COMPILE) -c $<
 
@@ -198,14 +219,14 @@ libguimodel.a: $(libguimodel_a_OBJECTS) $(libguimodel_a_DEPENDENCIES)
 	$(AR) cru libguimodel.a $(libguimodel_a_OBJECTS) $(libguimodel_a_LIBADD)
 	$(RANLIB) libguimodel.a
 
-mostlyclean-noinstPROGRAMS:
+mostlyclean-checkPROGRAMS:
 
-clean-noinstPROGRAMS:
-	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
+clean-checkPROGRAMS:
+	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)
 
-distclean-noinstPROGRAMS:
+distclean-checkPROGRAMS:
 
-maintainer-clean-noinstPROGRAMS:
+maintainer-clean-checkPROGRAMS:
 
 guimodeltest$(EXEEXT): $(guimodeltest_OBJECTS) $(guimodeltest_DEPENDENCIES)
 	@rm -f guimodeltest$(EXEEXT)
@@ -248,14 +269,9 @@ maintainer-clean-tags:
 
 distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
 
-subdir = src/guimodel
+subdir = qtgui/src/guimodel
 
 distdir: $(DISTFILES)
-	here=`cd $(top_builddir) && pwd`; \
-	top_distdir=`cd $(top_distdir) && pwd`; \
-	distdir=`cd $(distdir) && pwd`; \
-	cd $(top_srcdir) \
-	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu src/guimodel/Makefile
 	@for file in $(DISTFILES); do \
 	  d=$(srcdir); \
 	  if test -d $$d/$$file; then \
@@ -266,62 +282,142 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+actionsequencerwrapper.o: actionsequencerwrapper.cpp \
+	actionsequencerwrapper.h iscenesequencer.h \
+	../../../base/src/interfaces/isequenceupdatereceiver.h \
+	../../../base/src/interfaces/isequencercontrolsender.h \
+	../../../base/src/utils/autoptr.h ../../../config.h \
+	../../../base/src/interfaces/isequencercontrolreceiver.h \
+	iscenechangelistener.h
+controlmodel.o: controlmodel.cpp controlmodel.h point.h \
+	../../../base/src/interfaces/imoduledatareceiver.h \
+	../../../base/src/utils/autoptr.h ../../../config.h \
+	icontrolview.h icontrolconnectview.h \
+	../../../base/src/interfaces/imodelcontrolreceiver.h \
+	../../../base/src/utils/buffer.h \
+	../../../base/src/utils/bufferstream.h \
+	../../../base/src/utils/string_.h \
+	../../../base/src/utils/structreader.h
+controlvaluedispatcher.o: controlvaluedispatcher.cpp \
+	controlvaluedispatcher.h \
+	../../../base/src/interfaces/icontrolvaluereceiver.h point.h \
+	../../../base/src/utils/buffer.h \
+	../../../base/src/interfaces/imodelcontrolreceiver.h
+enginewrapper.o: enginewrapper.cpp ../../../config.h enginewrapper.h \
+	../../../base/src/utils/autoptr.h \
+	../../../util/include/basic_types.h \
+	../../../base/src/netinterfaces/controlvaluesendernet.h \
+	../../../base/src/interfaces/icontrolvaluesender.h \
+	../../../base/src/net/itaginterpreter.h \
+	../../../base/src/netinterfaces/modulestatisticssendernet.h \
+	../../../base/src/interfaces/imodulestatisticssender.h \
+	../../../base/src/netinterfaces/moduleclassnamesendernet.h \
+	../../../base/src/interfaces/imoduleclassnamesender.h \
+	../../../base/src/netinterfaces/moduleclassinfosendernet.h \
+	../../../base/src/interfaces/imoduleclassinfosender.h \
+	../../../base/src/netinterfaces/moduledatasendernet.h \
+	../../../base/src/interfaces/imoduledatasender.h \
+	../../../base/src/netinterfaces/moduleconstructiondumbsendernet.h \
+	../../../base/src/interfaces/imoduleconstructiondumbsender.h \
+	../../../base/src/netinterfaces/graphnamesendernet.h \
+	../../../base/src/interfaces/igraphnamesender.h \
+	../../../base/src/netinterfaces/sequenceupdatesendernet.h \
+	../../../base/src/interfaces/isequenceupdatesender.h \
+	../../../base/src/netinterfaces/sequencenamesendernet.h \
+	../../../base/src/interfaces/isequencenamesender.h \
+	../../../base/src/netinterfaces/errorsendernet.h \
+	../../../base/src/interfaces/ierrorsender.h \
+	../../../base/src/netinterfaces/modelstatussendernet.h \
+	../../../base/src/interfaces/imodelstatussender.h \
+	../../../base/src/netinterfaces/sequencerstatussendernet.h \
+	../../../base/src/interfaces/isequencerstatussender.h \
+	../../../base/src/netinterfaces/rendererstatussendernet.h \
+	../../../base/src/interfaces/irendererstatussender.h \
+	../../../base/src/netinterfaces/modelcontrolreceivernet.h \
+	../../../base/src/interfaces/imodelcontrolreceiver.h \
+	../../../base/src/netinterfaces/renderercontrolreceivernet.h \
+	../../../base/src/interfaces/irenderercontrolreceiver.h \
+	../../../base/src/netinterfaces/moduleclassloadercontrolreceivernet.h \
+	../../../base/src/interfaces/imoduleclassloadercontrolreceiver.h \
+	../../../base/src/netinterfaces/enginecontrolreceivernet.h \
+	../../../base/src/interfaces/ienginecontrolreceiver.h \
+	../../../base/src/netinterfaces/sequencercontrolreceivernet.h \
+	../../../base/src/interfaces/isequencercontrolreceiver.h \
+	../../../base/src/net/isocket.h \
+	../../../base/src/net/netexceptions.h \
+	../../../base/src/net/isender.h \
+	../../../base/src/net/sotimeout.h \
+	../../../base/src/net/protocol.h \
+	../../../base/src/net/idatalistener.h \
+	../../../base/src/net/tagger.h ../../../base/src/net/itagger.h \
+	../../../base/src/net/tagger.cpp \
+	../../../base/src/net/tagutils.h \
+	../../../base/src/net/tagdispatcher.h \
+	../../../base/src/net/tagdispatcher.cpp \
+	../../../base/src/net/socketadaptor.h \
+	../../../base/src/net/tcpclientsocket.h \
+	../../../base/src/net/iclientsocket.h \
+	../../../base/src/net/domainclientsocket.h graphmodel.h point.h \
+	../../../base/src/interfaces/imoduleconstructiondumbreceiver.h \
+	../../../base/src/interfaces/imoduledatareceiver.h \
+	controlmodel.h moduleclassmodel.h \
+	../../../base/src/interfaces/imoduleclassinforeceiver.h \
+	controlvaluedispatcher.h \
+	../../../base/src/interfaces/icontrolvaluereceiver.h \
+	../../../base/src/utils/buffer.h moduledatadispatcher.h
+graphmodel.o: graphmodel.cpp graphmodel.h point.h \
+	../../../base/src/interfaces/imodelcontrolreceiver.h \
+	../../../base/src/interfaces/imoduleconstructiondumbreceiver.h \
+	../../../base/src/interfaces/imoduledatareceiver.h igraphview.h \
+	../../../base/src/utils/buffer.h \
+	../../../base/src/utils/bufferstream.h
+moduleclassmodel.o: moduleclassmodel.cpp moduleclassmodel.h \
+	../../../base/src/interfaces/imoduleclassinforeceiver.h \
+	imoduleclassview.h moduleinfo.h pluginfo.h \
+	../../../base/src/utils/autoptr.h ../../../config.h xpm.h \
+	../../../base/src/utils/structreader.h \
+	../../../base/src/utils/stringtokenizer.h \
+	../../../base/src/utils/itokenizer.h \
+	../../../base/src/utils/buffer.h
+moduledatadispatcher.o: moduledatadispatcher.cpp moduledatadispatcher.h \
+	../../../base/src/interfaces/imoduledatareceiver.h
+moduleinfo.o: moduleinfo.cpp moduleinfo.h pluginfo.h \
+	../../../base/src/utils/autoptr.h ../../../config.h xpm.h
+point.o: point.cpp point.h
+xpm.o: xpm.cpp xpm.h
 
-DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-
--include $(DEP_FILES)
-
-mostlyclean-depend:
-
-clean-depend:
-
-distclean-depend:
-	-rm -rf .deps
-
-maintainer-clean-depend:
-
-%.o: %.c
-	@echo '$(COMPILE) -c $<'; \
-	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.c
-	@echo '$(LTCOMPILE) -c $<'; \
-	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
-
-%.o: %.cpp
-	@echo '$(CXXCOMPILE) -c $<'; \
-	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-cp .deps/$(*F).pp .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm .deps/$(*F).pp
-
-%.lo: %.cpp
-	@echo '$(LTCXXCOMPILE) -c $<'; \
-	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
-	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
-	  < .deps/$(*F).pp > .deps/$(*F).P; \
-	tr ' ' '\012' < .deps/$(*F).pp \
-	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
-	    >> .deps/$(*F).P; \
-	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -336,7 +432,7 @@ install-am: all-am
 install: install-am
 uninstall-am:
 uninstall: uninstall-am
-all-am: Makefile $(LIBRARIES) $(PROGRAMS)
+all-am: Makefile $(LIBRARIES)
 all-redirect: all-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
@@ -353,30 +449,28 @@ distclean-generic:
 
 maintainer-clean-generic:
 mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
-		mostlyclean-libtool mostlyclean-noinstPROGRAMS \
-		mostlyclean-tags mostlyclean-depend mostlyclean-generic
+		mostlyclean-libtool mostlyclean-checkPROGRAMS \
+		mostlyclean-tags mostlyclean-generic
 
 mostlyclean: mostlyclean-am
 
 clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
-		clean-noinstPROGRAMS clean-tags clean-depend \
-		clean-generic mostlyclean-am
+		clean-checkPROGRAMS clean-tags clean-generic \
+		mostlyclean-am
 
 clean: clean-am
 
 distclean-am:  distclean-noinstLIBRARIES distclean-compile \
-		distclean-libtool distclean-noinstPROGRAMS \
-		distclean-tags distclean-depend distclean-generic \
-		clean-am
+		distclean-libtool distclean-checkPROGRAMS \
+		distclean-tags distclean-generic clean-am
 	-rm -f libtool
 
 distclean: distclean-am
 
 maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
 		maintainer-clean-compile maintainer-clean-libtool \
-		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
-		maintainer-clean-depend maintainer-clean-generic \
-		distclean-am
+		maintainer-clean-checkPROGRAMS maintainer-clean-tags \
+		maintainer-clean-generic distclean-am
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
@@ -386,11 +480,10 @@ maintainer-clean: maintainer-clean-am
 clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
 mostlyclean-compile distclean-compile clean-compile \
 maintainer-clean-compile mostlyclean-libtool distclean-libtool \
-clean-libtool maintainer-clean-libtool mostlyclean-noinstPROGRAMS \
-distclean-noinstPROGRAMS clean-noinstPROGRAMS \
-maintainer-clean-noinstPROGRAMS tags mostlyclean-tags distclean-tags \
-clean-tags maintainer-clean-tags distdir mostlyclean-depend \
-distclean-depend clean-depend maintainer-clean-depend info-am info \
+clean-libtool maintainer-clean-libtool mostlyclean-checkPROGRAMS \
+distclean-checkPROGRAMS clean-checkPROGRAMS \
+maintainer-clean-checkPROGRAMS tags mostlyclean-tags distclean-tags \
+clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
 dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
 install-exec install-data-am install-data install-am install \
 uninstall-am uninstall all-redirect all-am all installdirs \
